/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sdegaonk' at '5/15/17 11:16 AM' with Gradle 2.14.1
 *
 * @author sdegaonk, @date 5/15/17 11:16 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
