import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sdegaonk' at '5/15/17 11:16 AM' with Gradle 2.14.1
 *
 * @author sdegaonk, @date 5/15/17 11:16 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        // TODO Auto-generated method stub
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
